# Generated by Django 5.0.6 on 2026-06-17 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('trade', models.CharField(choices=[('painting', 'Painting'), ('carpentry', 'Carpentry'), ('tiles', 'Tiles Fitting'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('other', 'Other')], default='other', max_length=30)),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True)),
                ('address', models.CharField(help_text='Short address', max_length=200)),
                ('pincode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('hired', 'Hired'), ('rejected', 'Not Suitable')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Worker Application',
                'verbose_name_plural': 'Worker Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
